[package]
name = "rust"
version = "0.1.0"
edition = "2021"
registries.crates-io.protocol = "sparse"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"

[[bin]]
name = "rust"
path = "main.rs"
